# Generated by Django 4.0.4 on 2022-05-12 02:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sprint_name', models.CharField(max_length=165, unique=True)),
                ('start_date', models.DateField(default=datetime.datetime(2022, 5, 12, 7, 49, 28, 909518))),
                ('end_date', models.DateField()),
            ],
        ),
    ]
