# Generated by Django 4.0.4 on 2022-05-12 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sprint', '0003_parameter_alter_sprint_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sprint.parameter')),
                ('sprint_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sprint.sprint')),
                ('vote_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_by', to=settings.AUTH_USER_MODEL)),
                ('vote_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
