# Generated by Django 4.0.4 on 2022-05-16 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sprint', '0004_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votes',
            name='vote_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vote_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
